; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting


[platformio]
default_envs = drone

[env:drone]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<DRONE/> -<GCS/>
build_flags = 
	-I include/common
	-I include/DRONE
    -I src/DRONE
lib_deps = 
	nrf24/RF24
	arduino-libraries/Servo@^1.3.0
	Wire


[env:gcs]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<GCS/> -<DRONE/>
build_flags = 
	-I include/common
	-I include/GCS
    -I src/GCS
lib_deps = 
	nrf24/RF24 
	https://github.com/tbekas/BLE-Gamepad-Client#main
	
[env:test]
platform = espressif32 
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<TEST/> -<GCS/> -<DRONE/>
build_flags = 
	-I include/common
	-I src/TEST
lib_deps = 
	nrf24/RF24